-- Orders table for post-purchase tracking
-- Run this in Supabase SQL Editor after inventory schema is created.

CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  stripe_session_id TEXT NOT NULL UNIQUE,
  stripe_payment_intent_id TEXT,
  item_code TEXT NOT NULL,
  buyer_email TEXT,
  amount_total INTEGER,
  order_status TEXT NOT NULL DEFAULT 'paid' CHECK (order_status IN ('paid', 'packed', 'shipped', 'delivered')),
  shipping_carrier TEXT,
  tracking_number TEXT,
  shipped_at TIMESTAMPTZ,
  CONSTRAINT orders_item_code_fk FOREIGN KEY (item_code) REFERENCES inventory(item_code)
);

CREATE INDEX IF NOT EXISTS idx_orders_item_code ON orders(item_code);
CREATE INDEX IF NOT EXISTS idx_orders_buyer_email ON orders(buyer_email);
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON orders(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_orders_order_status ON orders(order_status);

CREATE OR REPLACE FUNCTION update_orders_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS orders_updated_at ON orders;
CREATE TRIGGER orders_updated_at
  BEFORE UPDATE ON orders
  FOR EACH ROW
  EXECUTE FUNCTION update_orders_timestamp();

ALTER TABLE orders ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Service role can read/write orders"
  ON orders FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

-- Optional: allow anon authenticated reading for a future customer order-status page.
-- Keep disabled for now since this is an internal admin flow.
-- CREATE POLICY "Allow anon read orders"
--   ON orders FOR SELECT
--   TO anon
--   USING (true);
